### ISSUE TITLE
Bug in examples: Uncaught SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by WebrealizerZS** [webcomponents/gold-standard#17]
When you try executing this code 
```js
await import('./smart/component.m.js');
```
in browser (Chrome) it would through
```
Uncaught SyntaxError: await is only valid in async function
```

**Comment by JanMiksovsky** [comment]
Just wanted to confirm: are you referring to the example on https://github.com/webcomponents/gold-standard/wiki/Expressed-Dependencies?

Generally speaking, the code fragments provided aren't intended necessarily to be complete as is and ready for copy-and-pasting — it will almost always be necessary to provide additional code that depends on context. Still, if the `await` example on the above page was confusing to you, it might be worth expanding that particular example.

**Comment by JanMiksovsky** [comment]
I updated the sample code to sit inside an `async` function.
